### ISSUE TITLE
Status aktualisiert sich nicht

### ISSUE THREAD

**Issue by Standarduser** [foxriver76/ioBroker.loqed#1]
Wenn sich der Status des Schlosses ändert, wird der zugehörige Datenpunkt `loqed.0.lockMotor.currentPosition` in ioBroker nicht aktualisiert. Es spielt dabei keine Rolle, ob der Befehl über ioBroker oder die Loqed-App ausgelöst wurde. Der Wert ist erst wieder aktuell, wenn die Adapter-Instanz neugestartet wurde.

Die Statusabfrage an der Bridge zeigt stets den korrekten Wert.

**Comment by foxriver76** [comment]
Soweit ich mich erinnere und falls es sich nicht geändert hat musst du explizit definieren was LOQED an den Adapter sendet.

**Comment by Standarduser** [comment]
Ich hatte einen Typo in der Callback-URL. Der Status kommt nun nahezu ohne zeitliche Verzögerung.
Vielen Dank für den tollen Adapter.
