### ISSUE TITLE
Adaptereinstellungen verwirrend

### ISSUE THREAD

**Issue by mlapp** [foxriver76/ioBroker.loqed#4]
Ich habe seit heute auch ein LOQED Schloss installiert.
Der Adapter ist auch installiert. Aber da es keine Anleitung gibt und auch im Netz nicht viel zu LOQED und ioBroker zu finden ist. 
Ist unklar, welche Einstellungen im Adapter zu treffen sind. 
Was z.B. muss bei Port eingetragen werden? Stimmt die vorgeschlagene 9005? 
Steuern kann ich mein Schloss, das funktioniert problemlos. 
Allerdings bekomme ich im Datenpunkt loqed.0.lockMotor.currentPosition ein UNKNOWN oder auch mal ein DAY_LOCK, wenn ich an den Einstellungen rumspiele. Danach ändert sich der Wert aber nicht mehr. 
Solange currentPosition nicht aktuell gehalten wird, ist der Adapter für mich leider unbrauchbar. 
Kann mir da jemand weiter helfen?

Wird der Adapter eigentlich noch weiter entwickelt?

**Comment by foxriver76** [comment]
Ich wüsste nicht dass es neue Funktionalität gibt habe aber kein Schloss mehr.

Adapter öffnet einen Server auf definiertem Port, dann in LOQED Einstellungen deine iobroker url mit gegebenen Port angeben, und definieren welche Updates gesendet werden

**Comment by foxriver76** [comment]
Und das sollte in Einstellungen stehen, das sollte alles sein was zu tun ist: https://github.com/foxriver76/ioBroker.loqed/blob/5dc5231309ca9dcd99903b7673485c9a92e71ebe/admin/jsonConfig.json#L69

**Comment by Jey-Cee** [comment]
> Ansonsten checke in der bridge ob alle Updates angehakt sind und url Port mit iobroker übereinstimmt

Wie kommt man zu den Einstellungen? In der App hab ich dazu keine Möglichkeit.

**Comment by foxriver76** [comment]
https://github.com/foxriver76/ioBroker.loqed/blob/5dc5231309ca9dcd99903b7673485c9a92e71ebe/admin/jsonConfig.json#L79

**Comment by Jey-Cee** [comment]
Da war ich auch vorher schon, hab aber nichts gefunden. 

Man muss bei Outgoing Webhooks via LOQED Bridge auf Add/Delete webhooks gehen, dann sieht man welche Events denn Webhook auslösen. 

![grafik](https://github.com/foxriver76/ioBroker.loqed/assets/16007760/ffc68f41-5d2e-446f-a62e-08483323b420)

**Comment by foxriver76** [comment]
Dann bitte im anderen issue alle unknown events sammeln, dann kann ich diese implementieren

**Comment by Jey-Cee** [comment]
> Allerdings steht bei mir unter #Webhooks immer noch eine 0.

Das ist lediglich die ID Nummer des Webhooks.

**Comment by foxriver76** [comment]
Der Webhook wurde vom Adapter automatisch angelegt oder?

**Comment by foxriver76** [comment]
Ansonsten mache ich hier mal zu, dass `currentPosition` nicht aktuell ist, liegt an den nicht implementierten Events.

**Comment by Jey-Cee** [comment]
> Der Webhook wurde vom Adapter automatisch angelegt oder?

Ja bei mir auf jedenfall.
