### ISSUE TITLE
Event Type unknown 

### ISSUE THREAD

**Issue by Jey-Cee** [foxriver76/ioBroker.loqed#5]
Adapter throws message which says GO_TO_STATE_MANUAL_UNLOCK_VIA_OUTSIDE_MODULE_PIN is unknown.

2023-07-29 19:12:50.950 - warn: loqed.0 (413157) Unknown event: {"go_to_state":"OPEN","event_type":"GO_TO_STATE_MANUAL_UNLOCK_VIA_OUTSIDE_MODULE_PIN","mac_wifi":"70b8f61a44f8","mac_ble":"70b8f61a44fa","key_local_id":1}

**Comment by mlapp** [comment]
{"go_to_state":"OPEN","event_type":"GO_TO_STATE_MANUAL_UNLOCK_BLE_OPEN","mac_wifi":"70b8f61XXXXX","mac_ble":"70b8f61XXXXX","key_local_id":0}
{"go_to_state":"OPEN","event_type":"GO_TO_STATE_MANUAL_UNLOCK_VIA_OUTSIDE_MODULE_PIN","mac_wifi":"70b8f61XXXXX","mac_ble":"70b8f61XXXXX","key_local_id":0}
{"go_to_state":"NIGHT_LOCK","event_type":"GO_TO_STATE_MANUAL_UNLOCK_VIA_OUTSIDE_MODULE_BUTTON","mac_wifi":"70b8f61XXXXX","mac_ble":"70b8f61XXXXX","key_local_id":255}

Die hier habe ich in meinem Log gefunden. Vielleicht kannst du die ja schon mal einbauen. 

Ich behalte das Log aber mal im Auge, vielleicht kommen ja noch weitere Meldungen dazu. 

Auf jeden Fall schon mal besten Dank fürs Ergänzen des Adapters.

**Comment by foxriver76** [comment]
Bitte Version 0.2.2 probieren sobald verfügbar

**Comment by mlapp** [comment]
Hab ich jetzt mal installiert. Die Events scheinen keine Warnungen mehr auszulösen.
Werde die nächsten Tage die Funktion im Auge behalten und ob der Datenpunkt jetzt sauber gesetzt wird.
Danke für die schnelle Umsetzung
